# Generated by Django 6.0.5 on 2026-07-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('First_Secondary', 'First_Secondary'), ('Second_secondary', 'Second_secondary'), ('Third_Secondary', 'Third_Secondary')], max_length=100)),
                ('email', models.CharField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
