# Generated by Django 6.0.5 on 2026-07-25 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physic', '0002_question_user_created_at_user_image_user_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='LessonPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physic.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physic.user')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
