# Generated by Django 6.0.5 on 2026-07-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physic', '0003_remove_lesson_created_at_remove_lesson_link_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('live', 'Live')], default='recorded', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='live_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='live_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='meeting_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
