# Generated by Django 6.0.5 on 2026-07-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physic', '0004_lesson_lesson_type_lesson_live_date_lesson_live_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_pdfs/'),
        ),
    ]
