# Generated by Django 6.0.5 on 2026-07-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physic', '0005_lesson_pdf_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonpayment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonpayment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='lessonpayment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='lessonpayment',
            name='paid_at',
        ),
    ]
