# Generated by Django 6.0.5 on 2026-07-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physic', '0006_alter_lessonpayment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='homeworks/')),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physic.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
