# Generated by Django 6.0.5 on 2026-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physic', '0007_homework_delete_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
